In [1]:
# Import the lubraries 
import pandas as pd 
import matplotlib.pyplot as plt
import numpy as np

In [6]:
#Import the dataset 
dataset = pd.read_csv('house_prices_dataset.csv')
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [7]:
print(x)

[[3419 3 1 2 18.1 'Urban']
 [1256 3 2 8 1.2 'Suburban']
 [902 5 3 24 21.5 'Suburban']
 [3837 3 2 20 2.7 'Suburban']
 [1926 1 4 16 3.0 'Suburban']
 [1803 4 4 4 1.9 'Suburban']
 [1714 5 4 16 10.6 'Rural']
 [1371 1 2 37 15.9 'Rural']
 [3816 4 3 6 9.1 'Rural']
 [1219 1 2 6 15.1 'Rural']
 [3571 5 2 47 16.6 'Rural']
 [3833 3 3 32 22.0 'Suburban']
 [3033 5 4 5 26.6 'Urban']
 [1156 3 4 49 17.7 'Urban']
 [3218 5 3 35 8.0 'Suburban']
 [2528 2 2 50 14.7 'Urban']
 [930 1 2 9 12.8 'Urban']
 [922 1 4 9 3.7 'Rural']
 [1183 2 1 43 20.1 'Rural']
 [1695 3 1 31 11.3 'Rural']
 [1752 1 1 36 12.9 'Urban']
 [2869 2 2 11 26.1 'Rural']
 [3265 1 2 17 2.6 'Suburban']
 [908 4 4 34 20.0 'Urban']
 [3098 3 1 39 19.7 'Urban']
 [1614 4 4 28 2.8 'Rural']
 [3732 3 4 14 22.1 'Suburban']
 [3461 2 4 35 24.2 'Rural']
 [3672 3 3 49 4.2 'Rural']
 [3032 3 1 47 6.6 'Urban']
 [2518 2 1 45 16.6 'Urban']
 [1702 3 3 13 5.1 'Rural']
 [2639 1 3 46 6.3 'Urban']
 [3213 5 1 20 14.4 'Urban']
 [1939 2 3 26 26.4 'Urban']
 [826 5 4 43 3.2 '

In [8]:
print(y)

[712024 692683 648177 431737 373432 314181 802258 850981 429445 350280
 378517 515011 237235 804318 776856 414569 579434 431535 888387 176066
 109767 580547 751332 690341 204837 176819 663750 323508 630458 378082
 238890 465962 172132 356150 487477 398830 265409 559469 974244 669605
 837715 417212 741390 946305 785743 654634 108203 800305 956795 681542]


In [10]:
# Encoding the Independent variable
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[5])] ,remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [11]:
print(x)

[[0.0 0.0 1.0 3419 3 1 2 18.1]
 [0.0 1.0 0.0 1256 3 2 8 1.2]
 [0.0 1.0 0.0 902 5 3 24 21.5]
 [0.0 1.0 0.0 3837 3 2 20 2.7]
 [0.0 1.0 0.0 1926 1 4 16 3.0]
 [0.0 1.0 0.0 1803 4 4 4 1.9]
 [1.0 0.0 0.0 1714 5 4 16 10.6]
 [1.0 0.0 0.0 1371 1 2 37 15.9]
 [1.0 0.0 0.0 3816 4 3 6 9.1]
 [1.0 0.0 0.0 1219 1 2 6 15.1]
 [1.0 0.0 0.0 3571 5 2 47 16.6]
 [0.0 1.0 0.0 3833 3 3 32 22.0]
 [0.0 0.0 1.0 3033 5 4 5 26.6]
 [0.0 0.0 1.0 1156 3 4 49 17.7]
 [0.0 1.0 0.0 3218 5 3 35 8.0]
 [0.0 0.0 1.0 2528 2 2 50 14.7]
 [0.0 0.0 1.0 930 1 2 9 12.8]
 [1.0 0.0 0.0 922 1 4 9 3.7]
 [1.0 0.0 0.0 1183 2 1 43 20.1]
 [1.0 0.0 0.0 1695 3 1 31 11.3]
 [0.0 0.0 1.0 1752 1 1 36 12.9]
 [1.0 0.0 0.0 2869 2 2 11 26.1]
 [0.0 1.0 0.0 3265 1 2 17 2.6]
 [0.0 0.0 1.0 908 4 4 34 20.0]
 [0.0 0.0 1.0 3098 3 1 39 19.7]
 [1.0 0.0 0.0 1614 4 4 28 2.8]
 [0.0 1.0 0.0 3732 3 4 14 22.1]
 [1.0 0.0 0.0 3461 2 4 35 24.2]
 [1.0 0.0 0.0 3672 3 3 49 4.2]
 [0.0 0.0 1.0 3032 3 1 47 6.6]
 [0.0 0.0 1.0 2518 2 1 45 16.6]
 [1.0 0.0 0.0 1702 3 3 13 5.1]


In [12]:
# Splitting the dataset
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [13]:
# Import the model 
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()

In [14]:
regressor.fit(x_train,y_train)

LinearRegression()

In [15]:
y_pred = regressor.predict(x_test)

In [21]:
np.printoptions(precisions=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[339460.64512    630458.        ]
 [658022.58371696 515011.        ]
 [501535.37302108 378517.        ]
 [464976.79778026 417212.        ]
 [866013.22786309 648177.        ]
 [539297.03656587 323508.        ]
 [297725.93116945 974244.        ]
 [481552.97136778 465962.        ]
 [472683.63510358 751332.        ]
 [558892.95268029 373432.        ]]
