In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [16]:
dataset = pd.read_csv('Monthly_expenditure.csv')
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [33]:
print(x)
print(x.shape)

[[   56 87563     6]
 [   46 22695     8]
 [   32 68190     5]
 [   60 25258     4]
 [   25 59504     2]
 [   38 53159     6]
 [   56 33986     6]
 [   36 81858     3]
 [   40 32666     7]
 [   28 58660     8]
 [   28 23561     8]
 [   41 46854     1]
 [   53 84505     1]
 [   57 72251     4]
 [   41 42662     3]
 [   20 28392     6]
 [   39 50535     8]
 [   19 98603     5]
 [   41 72256     3]
 [   61 55222     4]
 [   47 97373     4]
 [   55 99575     3]
 [   19 83335     4]
 [   38 30965     3]
 [   50 44538     2]
 [   29 90592     3]
 [   39 28110     7]
 [   61 99309     3]
 [   42 47266     4]
 [   44 72992     8]
 [   59 26910     7]
 [   45 20206     4]
 [   33 43419     1]
 [   32 70636     1]
 [   64 70015     8]
 [   61 74268     8]
 [   20 38141     7]
 [   54 91910     2]
 [   24 76044     8]
 [   38 87214     1]
 [   26 53827     3]
 [   56 75820     4]
 [   35 82623     1]
 [   21 95450     1]
 [   42 42299     2]
 [   31 63585     7]
 [   26 84044     7]
 [   43 62557

In [34]:
print(y)
print(y.shape)

[4042.66181306 2586.9859609  3033.9318087  2502.01701203 1824.0651869
 3018.12247489 3268.35364246 2810.25047001 2661.34107358 3554.18564369
 2758.06805925 2569.29904288 2686.38596785 3529.09744841 2336.41818143
 2179.69625681 3572.8024437  3346.11492846 2477.844758   2954.96849438
 3960.34668946 3925.90578076 2772.07616207 2080.01941283 2847.5476093
 2985.60264037 2739.88333604 3844.29974102 2706.71514191 3870.05976345
 3239.42587262 1715.27408125 1795.65975276 2262.84596218 4236.80860462
 4210.30853032 2440.94532482 3155.49578061 3137.26635036 2650.67632963
 2415.80595791 3369.31779519 2679.48251018 2312.95982599 1824.84048919
 3141.54763139 3395.78002606 3074.53207773 2251.5548077  2149.64486878
 3949.87132501 2660.41634875 3589.85946623 2591.63983613 2700.02687571
 2339.93913084 2729.03807709 3197.88496493 1607.81025022 2217.63823389
 3003.14953123 2760.35905316 2398.91749254 2905.8333652  3724.90767736
 2074.64873036 3622.01244269 1974.68517337 3712.80291167 2414.54460089
 1721.07

In [35]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(80, 3)
(80,)
(20, 3)
(20,)


In [36]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train,y_train)

LinearRegression()

In [37]:
y_pred = regressor.predict(x_test)

In [39]:
# plt.scatter(x_test,y_pred,color='red')
# plt.plot([t_test.min(),y_test.max()],[y_test.min(),y_test.max()],color='blue')
# plt.title('Truth vs Bluff(Training set)')
# plt.xlabel('resources')
# plt.ylabel('Expenditure')
# plt.show()
# Plot actual vs. predicted values
# plt.figure(figsize=(10, 6))
# plt.scatter(y_test, y_pred, color="blue", alpha=0.7)
# plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], color="red", linewidth=2)  # Perfect fit line
# plt.title("Actual vs Predicted Monthly Expenditure")
# plt.xlabel("Actual Values")
# plt.ylabel("Predicted Values")
# plt.grid()
# plt.show()

In [40]:
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[3364.62 3135.96]
 [2985.52 2591.64]
 [1898.63 1721.07]
 [3226.45 3141.55]
 [2191.12 1824.84]
 [2763.6  2650.68]
 [2807.28 2772.08]
 [2791.02 2524.98]
 [2593.47 2758.07]
 [4037.04 4042.66]
 [2901.64 2477.84]
 [3150.52 3239.43]
 [3822.16 4031.58]
 [2325.83 2262.85]
 [2962.31 2962.05]
 [2143.17 1824.07]
 [3046.64 3040.3 ]
 [3741.48 3779.56]
 [3037.64 2686.39]
 [2196.59 1715.27]]
