In [28]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [29]:
dataset = pd.read_csv('SeoulBikeData.csv')

In [30]:
dataset.isnull().sum()

Date                         0
Rented Bike Count            0
Hour                         0
Temperature(°C)              0
Humidity(%)                  0
Wind speed (m/s)             0
Visibility (10m)             0
Dew point temperature(°C)    0
Solar Radiation (MJ/m2)      0
Rainfall(mm)                 0
Snowfall (cm)                0
Seasons                      0
Holiday                      0
Functioning Day              0
dtype: int64

In [31]:
dataset.head()

Date  Rented Bike Count  Hour  Temperature(°C)  Humidity(%)  \
0  01/12/2017                254     0             -5.2           37   
1  01/12/2017                204     1             -5.5           38   
2  01/12/2017                173     2             -6.0           39   
3  01/12/2017                107     3             -6.2           40   
4  01/12/2017                 78     4             -6.0           36   

   Wind speed (m/s)  Visibility (10m)  Dew point temperature(°C)  \
0               2.2              2000                      -17.6   
1               0.8              2000                      -17.6   
2               1.0              2000                      -17.7   
3               0.9              2000                      -17.6   
4               2.3              2000                      -18.6   

   Solar Radiation (MJ/m2)  Rainfall(mm)  Snowfall (cm) Seasons     Holiday  \
0                      0.0           0.0            0.0  Winter  No Holiday   
1                      0.0           0.0            0.0  Winter  No Holiday   
2                      0.0           0.0            0.0  Winter  No Holiday   
3                      0.0           0.0            0.0  Winter  No Holiday   
4                      0.0           0.0            0.0  Winter  No Holiday   

  Functioning Day  
0             Yes  
1             Yes  
2             Yes  
3             Yes  
4             Yes

In [47]:
dataset.drop('Date',inplace=True,axis=1)

In [48]:
x = dataset.iloc[:,:-1]. values
y = dataset.iloc[:,-1].values

In [49]:
print(x)

[[254 0 -5.2 ... 0.0 'Winter' 'No Holiday']
 [204 1 -5.5 ... 0.0 'Winter' 'No Holiday']
 [173 2 -6.0 ... 0.0 'Winter' 'No Holiday']
 ...
 [694 21 2.6 ... 0.0 'Autumn' 'No Holiday']
 [712 22 2.1 ... 0.0 'Autumn' 'No Holiday']
 [584 23 1.9 ... 0.0 'Autumn' 'No Holiday']]


In [50]:
print(y)

['Yes' 'Yes' 'Yes' ... 'Yes' 'Yes' 'Yes']


In [52]:
# Encoading the matrix of features x 
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(sparse_output=True),[10,11])],remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [53]:
print(x)

[[0.0 0.0 0.0 ... 0.0 0.0 0.0]
 [0.0 0.0 0.0 ... 0.0 0.0 0.0]
 [0.0 0.0 0.0 ... 0.0 0.0 0.0]
 ...
 [1.0 0.0 0.0 ... 0.0 0.0 0.0]
 [1.0 0.0 0.0 ... 0.0 0.0 0.0]
 [1.0 0.0 0.0 ... 0.0 0.0 0.0]]


In [54]:
# Encoding matrix of features y
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [55]:
print(y)

[1 1 1 ... 1 1 1]


In [57]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [58]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()

In [59]:
regressor.fit(x_train,y_train)

LinearRegression()

In [26]:
y_pred = regressor.predict(x_test)

In [27]:
print(y_pred)

[ 1.44535219e+06  1.48596637e+06  2.26737078e+05  1.79942733e+06
  3.28540232e+05  2.17445183e+05  1.33132641e+06  3.24255554e+05
  1.57518564e+06  4.59430055e+05  1.12744249e+05  4.68808501e+05
  1.34626557e+06  5.91877934e+05  5.63547654e+04  5.24356721e+05
  5.23108993e+05  4.47803191e+05 -1.60324069e+04  6.13015622e+05
 -3.20238859e+05  5.24128015e+05  4.95509807e+05  5.41608860e+05
  1.18670383e+06  1.27112778e+06  5.79137371e+05  6.04794715e+05
  5.21727061e+05  4.33295956e+05  4.19071138e+05  4.96638348e+05
  5.25402916e+05  7.18049032e+05  2.30775075e+05  5.86081022e+05
  3.38331412e+05  2.67003021e+04  9.54236724e+04  4.19967308e+05
  1.33707273e+05  6.48700268e+05  5.38715786e+05  1.42934193e+06
  4.01310671e+05  2.60279275e+05 -6.55335596e+04  3.00922929e+05
  5.20140646e+05  3.47025338e+05  7.28684585e+04  4.93231791e+05
  5.10072853e+05  8.27761012e+05  5.50479884e+05  4.56539648e+05
  1.79942733e+06  3.33124813e+05  3.73708279e+05  4.25018130e+05
  3.81509323e+05  8.68188